apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: pdlc
  annotations:
    tilt.dev/down-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temporal-postgres-data
  namespace: pdlc
  annotations:
    tilt.dev/down-policy: keep
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 5Gi
